language: node_js
node_js:
  - "0.11"
  - "0.10"
deploy:
  provider: npm
  email: damien.berseron@me.com
  api_key:
    secure: "Pc9sD/q1rSAEuhXnPXElPnIVOhziVQu9QGNG9G6hoQeAFTxtGY9QebTaiXej0s+am3Z3FjhzNBbbwP+aV8SD0eJL0eQO3cOmfzOtLGt9qGIHTRSeDo7Ys3D/JOceXOjCmFmJJrVCIbGxry/oeTal75uQeslONrRJt9ke8pw9NKM="
  on:
    branch: master
